// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKENAe2TqfoWJftfKK5E66UZMKI0GT7iY',
    appId: '1:520970428188:web:af740fad484dc06c3124d9',
    messagingSenderId: '520970428188',
    projectId: 'fir-setup-3cb9f',
    authDomain: 'fir-setup-3cb9f.firebaseapp.com',
    storageBucket: 'fir-setup-3cb9f.appspot.com',
    measurementId: 'G-N1JT678JZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC1c9DPzb6PpZAfwdEk1TqN9EOrIvaJdI',
    appId: '1:520970428188:android:4fb0045d85857ba93124d9',
    messagingSenderId: '520970428188',
    projectId: 'fir-setup-3cb9f',
    storageBucket: 'fir-setup-3cb9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEAAcULMvV_Xzie0CIaAMVW1rzSzYmvps',
    appId: '1:520970428188:ios:8ff40641f3320fad3124d9',
    messagingSenderId: '520970428188',
    projectId: 'fir-setup-3cb9f',
    storageBucket: 'fir-setup-3cb9f.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCli',
  );
}
